### ISSUE TITLE
Upgrade siddhi to 3.1.0

### ISSUE THREAD

**Issue by bhack** [Stratio/Decision#25]
With siddhi 3.1.0 introduction of event table will be possibile some workaround to catch non occurencies. See https://github.com/Stratio/streaming-cep-engine/issues/24 and [this thread](http://osdir.com/ml/carbon-wso2-architecture/2013-07/msg00287.html)

**Comment by bhack** [comment]
What is happening with production cep? Is this the new siddhi?https://github.com/wso2/product-cep

**Comment by dmorales-stratio** [comment]
They are now working on github, instead of subversion, and they are going to release a 3.0 version of siddhi.

We are now working with a private (wso2) repo to add siddhi as dependency and it seems to be outdated/not aligned with maven central.

Next step is to ask to WSO2 what is the best thing to do.

**Comment by bhack** [comment]
Seems that there is some nonalignment between MavenCentral/Ws02 repository. But [here](http://maven.wso2.org/nexus/content/repositories/releases) i see that siddhi 3.1.0 was released in april 2014.

**Comment by dmorales-stratio** [comment]
I can only see 2.2.0

http://maven.wso2.org/nexus/content/repositories/releases/org/wso2/siddhi/siddhi-core/

Am i missing something?

**Comment by bhack** [comment]
Exactly bit download and [release note](http://product-dist.wso2.com/products/complex-event-processor/3.1.0/release-notes.html) are on 3.1.0

**Comment by bhack** [comment]
Probably i see some future overlap between stratio effort and [wso2 analytics plans] (http://srinathsview.blogspot.it/2015/03/introducing-wso2-analytics-platform.html).
I really hope the you can continue to share with wso2 the same siddhi core.

**Comment by bhack** [comment]
@suhothayan What is the last official released version? Why is not synced with maven repositories?
